"""
``dump.cs`` - the main artefact of an IL2CPP dump.

The output is byte-for-byte compatible with the reference Il2CppDumper layout so
existing tooling (search snippets, dnSpy cross-references, tutorials) keeps
working::

    // Namespace: UnityEngine
    public class Transform : Component, IEnumerable
     // TypeDefIndex: 1234
    {
        // Fields
        private IntPtr m_InternalPtr; // 0x10

        // Properties
        public Vector3 position { get; set; }

        // Methods
        // RVA: 0x1A2B3C Offset: 0x1A1B3C VA: 0x1A2B3C Slot: 4
        public Vector3 get_position() { }
    }
"""

from __future__ import annotations

from typing import Any, Callable, Dict, List, Optional

from .. import consts
from ..executor import Executor

Progress = Optional[Callable[[float, str], None]]


class DumpConfig:
    """Which parts of the metadata should end up in ``dump.cs``."""

    __slots__ = ("dump_field", "dump_property", "dump_method", "dump_attribute",
                 "dump_field_offset", "dump_method_offset", "dump_type_def_index")

    def __init__(self, dump_field: bool = True, dump_property: bool = True,
                 dump_method: bool = True, dump_attribute: bool = True,
                 dump_field_offset: bool = True, dump_method_offset: bool = True,
                 dump_type_def_index: bool = True):
        self.dump_field = dump_field
        self.dump_property = dump_property
        self.dump_method = dump_method
        self.dump_attribute = dump_attribute
        self.dump_field_offset = dump_field_offset
        self.dump_method_offset = dump_method_offset
        self.dump_type_def_index = dump_type_def_index

    @staticmethod
    def from_dict(values: Dict[str, Any]) -> "DumpConfig":
        return DumpConfig(
            dump_field=bool(values.get("dumpField", True)),
            dump_property=bool(values.get("dumpProperty", True)),
            dump_method=bool(values.get("dumpMethod", True)),
            dump_attribute=bool(values.get("dumpAttribute", True)),
            dump_field_offset=bool(values.get("dumpFieldOffset", True)),
            dump_method_offset=bool(values.get("dumpMethodOffset", True)),
            dump_type_def_index=bool(values.get("dumpTypeDefIndex", True)),
        )


def write_dump_cs(executor: Executor, config: DumpConfig, path: str,
                  progress: Progress = None) -> Dict[str, int]:
    metadata = executor.metadata
    il2cpp = executor.il2cpp
    full = executor.has_types
    method_modifiers: Dict[int, str] = {}

    counters = {"types": 0, "fields": 0, "methods": 0, "properties": 0}
    images = metadata.imageDefs
    total = max(1, len(images))

    with open(path, "w", encoding="utf-8", newline="\n") as out:
        write = out.write

        write("// Generated by IL2CPP Dumper Studio\n")
        write("// Developer: Mohamed Annati\n")
        write("// Metadata version: %s | Mode: %s\n"
              % (metadata.version, executor.mode()))
        if not full:
            write("// NOTE: the native binary could not be resolved, so type\n")
            write("//       signatures are shown as TypeIndex markers.\n")

        for image_index, image_def in enumerate(images):
            write("// Image %d: %s - %d\n"
                  % (image_index, metadata.get_string_from_index(image_def["nameIndex"]),
                     image_def["typeStart"]))

        for image_index, image_def in enumerate(images):
            image_name = metadata.get_string_from_index(image_def["nameIndex"])
            type_end = image_def["typeStart"] + image_def["typeCount"]
            try:
                for type_def_index in range(image_def["typeStart"], type_end):
                    if type_def_index >= len(metadata.typeDefs):
                        break
                    type_def = metadata.typeDefs[type_def_index]
                    extends: List[str] = []

                    if full and type_def["parentIndex"] >= 0:
                        parent = executor.type_at(type_def["parentIndex"])
                        parent_name = executor.get_type_name(parent, False, False)
                        if (not _is_value_type(type_def) and not _is_enum(type_def)
                                and parent_name != "object"):
                            extends.append(parent_name)

                    if full and type_def["interfaces_count"] > 0:
                        for i in range(type_def["interfaces_count"]):
                            slot = type_def["interfacesStart"] + i
                            if 0 <= slot < len(metadata.interfaceIndices):
                                entry = executor.type_at(metadata.interfaceIndices[slot])
                                extends.append(executor.get_type_name(entry, False, False))

                    write("\n// Namespace: %s\n"
                          % metadata.get_string_from_index(type_def["namespaceIndex"]))

                    if config.dump_attribute and _is_serializable(type_def):
                        write("[Serializable]\n")
                    write(_type_visibility(type_def))
                    write(_type_kind(type_def))
                    write(executor.get_type_def_name(type_def, False, True))
                    if extends:
                        write(" : %s" % ", ".join(extends))
                    if config.dump_type_def_index:
                        write(" // TypeDefIndex: %d\n{" % type_def_index)
                    else:
                        write("\n{")
                    counters["types"] += 1

                    # ---------------- fields ----------------
                    if config.dump_field and type_def["field_count"] > 0:
                        write("\n\t// Fields\n")
                        for i in range(type_def["fieldStart"],
                                       type_def["fieldStart"] + type_def["field_count"]):
                            if i >= len(metadata.fieldDefs):
                                break
                            field_def = metadata.fieldDefs[i]
                            field_type = executor.type_at(field_def["typeIndex"])
                            is_static = False
                            is_const = False
                            write("\t")
                            if full and field_type is not None:
                                attrs = field_type["attrs"]
                                write(_field_access(attrs))
                                if attrs & consts.FIELD_ATTRIBUTE_LITERAL:
                                    is_const = True
                                    write("const ")
                                else:
                                    if attrs & consts.FIELD_ATTRIBUTE_STATIC:
                                        is_static = True
                                        write("static ")
                                    if attrs & consts.FIELD_ATTRIBUTE_INIT_ONLY:
                                        write("readonly ")
                                write("%s %s" % (
                                    executor.get_type_name(field_type, False, False),
                                    metadata.get_string_from_index(field_def["nameIndex"])))
                            else:
                                write("object %s"
                                      % metadata.get_string_from_index(field_def["nameIndex"]))
                                write(" /* TypeIndex: %d */" % field_def["typeIndex"])

                            default = metadata.get_field_default_value(i)
                            if default is not None and default["dataIndex"] != -1 and full:
                                ok, value = executor.try_get_default_value(
                                    default["typeIndex"], default["dataIndex"])
                                write(" = " + format_constant(ok, value))

                            if config.dump_field_offset and not is_const and full:
                                offset = il2cpp.get_field_offset_from_index(
                                    type_def_index, i - type_def["fieldStart"], i,
                                    _is_value_type(type_def), is_static)
                                write("; // 0x%X\n" % offset)
                            else:
                                write(";\n")
                            counters["fields"] += 1

                    # ---------------- properties ----------------
                    if config.dump_property and type_def["property_count"] > 0:
                        write("\n\t// Properties\n")
                        for i in range(type_def["propertyStart"],
                                       type_def["propertyStart"] + type_def["property_count"]):
                            if i >= len(metadata.propertyDefs):
                                break
                            property_def = metadata.propertyDefs[i]
                            write("\t")
                            if full:
                                if property_def["get"] >= 0:
                                    method_index = type_def["methodStart"] + property_def["get"]
                                    if method_index < len(metadata.methodDefs):
                                        method_def = metadata.methodDefs[method_index]
                                        write(_method_modifiers(method_def, method_modifiers))
                                        property_type = executor.type_at(method_def["returnType"])
                                        write("%s %s { " % (
                                            executor.get_type_name(property_type, False, False),
                                            metadata.get_string_from_index(
                                                property_def["nameIndex"])))
                                elif property_def["set"] >= 0:
                                    method_index = type_def["methodStart"] + property_def["set"]
                                    if method_index < len(metadata.methodDefs):
                                        method_def = metadata.methodDefs[method_index]
                                        write(_method_modifiers(method_def, method_modifiers))
                                        parameter_index = method_def["parameterStart"]
                                        property_type = None
                                        if parameter_index < len(metadata.parameterDefs):
                                            property_type = executor.type_at(
                                                metadata.parameterDefs[parameter_index]["typeIndex"])
                                        write("%s %s { " % (
                                            executor.get_type_name(property_type, False, False),
                                            metadata.get_string_from_index(
                                                property_def["nameIndex"])))
                                else:
                                    write("object %s { "
                                          % metadata.get_string_from_index(
                                              property_def["nameIndex"]))
                            else:
                                write("object %s { "
                                      % metadata.get_string_from_index(property_def["nameIndex"]))
                            if property_def["get"] >= 0:
                                write("get; ")
                            if property_def["set"] >= 0:
                                write("set; ")
                            write("}\n")
                            counters["properties"] += 1

                    # ---------------- events ----------------
                    if config.dump_property and type_def["event_count"] > 0:
                        write("\n\t// Events\n")
                        for i in range(type_def["eventStart"],
                                       type_def["eventStart"] + type_def["event_count"]):
                            if i >= len(metadata.eventDefs):
                                break
                            event_def = metadata.eventDefs[i]
                            event_type = executor.type_at(event_def["typeIndex"])
                            write("\t%s %s;\n" % (
                                executor.get_type_name(event_type, False, False)
                                if full else "object",
                                metadata.get_string_from_index(event_def["nameIndex"])))

                    # ---------------- methods ----------------
                    if config.dump_method and type_def["method_count"] > 0:
                        write("\n\t// Methods\n")
                        for i in range(type_def["methodStart"],
                                       type_def["methodStart"] + type_def["method_count"]):
                            if i >= len(metadata.methodDefs):
                                break
                            write("\n")
                            method_def = metadata.methodDefs[i]
                            is_abstract = bool(method_def["flags"]
                                               & consts.METHOD_ATTRIBUTE_ABSTRACT)

                            if config.dump_method_offset and full:
                                method_pointer = il2cpp.get_method_pointer(image_name,
                                                                           method_def, i)
                                if not is_abstract and method_pointer > 0:
                                    fixed_pointer = il2cpp.get_rva(method_pointer)
                                    try:
                                        file_offset = il2cpp.map_vatr(method_pointer)
                                    except (ValueError, IndexError):
                                        file_offset = 0
                                    write("\t// RVA: 0x%X Offset: 0x%X VA: 0x%X"
                                          % (fixed_pointer, file_offset, method_pointer))
                                else:
                                    write("\t// RVA: -1 Offset: -1")
                                if method_def["slot"] != 0xFFFF:
                                    write(" Slot: %d" % method_def["slot"])
                                write("\n")

                            write("\t")
                            write(_method_modifiers(method_def, method_modifiers))
                            return_type = executor.type_at(method_def["returnType"])
                            method_name = metadata.get_string_from_index(
                                method_def["nameIndex"])
                            if method_def["genericContainerIndex"] >= 0:
                                container = executor._generic_container(
                                    method_def["genericContainerIndex"])
                                if container is not None:
                                    method_name += executor._generic_container_params(container)
                            if full and return_type is not None and return_type["byref"] == 1:
                                write("ref ")
                            write("%s %s(" % (
                                executor.get_type_name(return_type, False, False) if full
                                else "object",
                                method_name))

                            parameters: List[str] = []
                            for j in range(method_def["parameterCount"]):
                                parameter_index = method_def["parameterStart"] + j
                                if parameter_index >= len(metadata.parameterDefs):
                                    break
                                parameter_def = metadata.parameterDefs[parameter_index]
                                parameter_name = metadata.get_string_from_index(
                                    parameter_def["nameIndex"])
                                parameter_type = executor.type_at(parameter_def["typeIndex"])
                                chunk = ""
                                if full and parameter_type is not None:
                                    type_name = executor.get_type_name(parameter_type,
                                                                      False, False)
                                    attrs = parameter_type["attrs"]
                                    if parameter_type["byref"] == 1:
                                        if (attrs & consts.PARAM_ATTRIBUTE_OUT) and not (
                                                attrs & consts.PARAM_ATTRIBUTE_IN):
                                            chunk += "out "
                                        elif not (attrs & consts.PARAM_ATTRIBUTE_OUT) and (
                                                attrs & consts.PARAM_ATTRIBUTE_IN):
                                            chunk += "in "
                                        else:
                                            chunk += "ref "
                                    else:
                                        if attrs & consts.PARAM_ATTRIBUTE_IN:
                                            chunk += "[In] "
                                        if attrs & consts.PARAM_ATTRIBUTE_OUT:
                                            chunk += "[Out] "
                                    chunk += "%s %s" % (type_name, parameter_name)
                                else:
                                    chunk += "object %s" % parameter_name
                                default = metadata.get_parameter_default_value(parameter_index)
                                if default is not None and default["dataIndex"] != -1 and full:
                                    ok, value = executor.try_get_default_value(
                                        default["typeIndex"], default["dataIndex"])
                                    chunk += " = " + format_constant(ok, value)
                                parameters.append(chunk)
                            write(", ".join(parameters))
                            write(");\n" if is_abstract else ") { }\n")
                            counters["methods"] += 1

                            if full:
                                specs = il2cpp.method_definition_method_specs.get(i)
                                if specs:
                                    write("\t/* GenericInstMethod :\n")
                                    seen = set()
                                    for spec in specs:
                                        spec_index = il2cpp.method_specs.index(spec) \
                                            if len(il2cpp.method_specs) < 200000 else -1
                                        pointer = il2cpp.method_spec_generic_method_pointers.get(
                                            spec_index, 0)
                                        key = pointer
                                        if key in seen:
                                            type_name, spec_method = \
                                                executor.get_method_spec_name(spec_index)
                                            write("\t|-%s.%s\n" % (type_name, spec_method))
                                            continue
                                        seen.add(key)
                                        write("\t|\n")
                                        if pointer > 0:
                                            fixed_pointer = il2cpp.get_rva(pointer)
                                            try:
                                                file_offset = il2cpp.map_vatr(pointer)
                                            except (ValueError, IndexError):
                                                file_offset = 0
                                            write("\t|-RVA: 0x%X Offset: 0x%X VA: 0x%X\n"
                                                  % (fixed_pointer, file_offset, pointer))
                                        else:
                                            write("\t|-RVA: -1 Offset: -1\n")
                                        type_name, spec_method = executor.get_method_spec_name(
                                            spec_index)
                                        write("\t|-%s.%s\n" % (type_name, spec_method))
                                    write("\t*/\n")

                    write("}\n")
            except Exception as error:  # keep going, exactly like the original
                write("/*\n%s\n*/\n}\n" % error)

            if progress is not None:
                progress((image_index + 1) / total,
                         "dump.cs - %s" % image_name)

    return counters


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def _is_value_type(type_def: Dict[str, Any]) -> bool:
    return (type_def["bitfield"] & 0x1) == 1


def _is_enum(type_def: Dict[str, Any]) -> bool:
    return ((type_def["bitfield"] >> 1) & 0x1) == 1


def _is_serializable(type_def: Dict[str, Any]) -> bool:
    return bool(type_def["flags"] & consts.TYPE_ATTRIBUTE_SERIALIZABLE)


def _type_visibility(type_def: Dict[str, Any]) -> str:
    visibility = type_def["flags"] & consts.TYPE_ATTRIBUTE_VISIBILITY_MASK
    return {
        consts.TYPE_ATTRIBUTE_PUBLIC: "public ",
        consts.TYPE_ATTRIBUTE_NESTED_PUBLIC: "public ",
        consts.TYPE_ATTRIBUTE_NOT_PUBLIC: "internal ",
        consts.TYPE_ATTRIBUTE_NESTED_FAM_AND_ASSEM: "internal ",
        consts.TYPE_ATTRIBUTE_NESTED_ASSEMBLY: "internal ",
        consts.TYPE_ATTRIBUTE_NESTED_PRIVATE: "private ",
        consts.TYPE_ATTRIBUTE_NESTED_FAMILY: "protected ",
        consts.TYPE_ATTRIBUTE_NESTED_FAM_OR_ASSEM: "protected internal ",
    }.get(visibility, "")


def _type_kind(type_def: Dict[str, Any]) -> str:
    flags = type_def["flags"]
    if flags & consts.TYPE_ATTRIBUTE_ABSTRACT and flags & consts.TYPE_ATTRIBUTE_SEALED:
        prefix = "static "
    elif not (flags & consts.TYPE_ATTRIBUTE_INTERFACE) and flags & consts.TYPE_ATTRIBUTE_ABSTRACT:
        prefix = "abstract "
    elif (not _is_value_type(type_def) and not _is_enum(type_def)
          and flags & consts.TYPE_ATTRIBUTE_SEALED):
        prefix = "sealed "
    else:
        prefix = ""
    if flags & consts.TYPE_ATTRIBUTE_INTERFACE:
        return prefix + "interface "
    if _is_enum(type_def):
        return prefix + "enum "
    if _is_value_type(type_def):
        return prefix + "struct "
    return prefix + "class "


def _field_access(attrs: int) -> str:
    return {
        consts.FIELD_ATTRIBUTE_PRIVATE: "private ",
        consts.FIELD_ATTRIBUTE_PUBLIC: "public ",
        consts.FIELD_ATTRIBUTE_FAMILY: "protected ",
        consts.FIELD_ATTRIBUTE_ASSEMBLY: "internal ",
        consts.FIELD_ATTRIBUTE_FAM_AND_ASSEM: "internal ",
        consts.FIELD_ATTRIBUTE_FAM_OR_ASSEM: "protected internal ",
    }.get(attrs & consts.FIELD_ATTRIBUTE_FIELD_ACCESS_MASK, "")


def _method_modifiers(method_def: Dict[str, Any], cache: Dict[int, str]) -> str:
    key = id(method_def)
    if key in cache:
        return cache[key]
    flags = method_def["flags"]
    text = {
        consts.METHOD_ATTRIBUTE_PRIVATE: "private ",
        consts.METHOD_ATTRIBUTE_PUBLIC: "public ",
        consts.METHOD_ATTRIBUTE_FAMILY: "protected ",
        consts.METHOD_ATTRIBUTE_ASSEM: "internal ",
        consts.METHOD_ATTRIBUTE_FAM_AND_ASSEM: "internal ",
        consts.METHOD_ATTRIBUTE_FAM_OR_ASSEM: "protected internal ",
    }.get(flags & consts.METHOD_ATTRIBUTE_MEMBER_ACCESS_MASK, "")

    if flags & consts.METHOD_ATTRIBUTE_STATIC:
        text += "static "
    if flags & consts.METHOD_ATTRIBUTE_ABSTRACT:
        text += "abstract "
        if (flags & consts.METHOD_ATTRIBUTE_VTABLE_LAYOUT_MASK) == consts.METHOD_ATTRIBUTE_REUSE_SLOT:
            text += "override "
    elif flags & consts.METHOD_ATTRIBUTE_FINAL:
        if (flags & consts.METHOD_ATTRIBUTE_VTABLE_LAYOUT_MASK) == consts.METHOD_ATTRIBUTE_REUSE_SLOT:
            text += "sealed override "
    elif flags & consts.METHOD_ATTRIBUTE_VIRTUAL:
        if (flags & consts.METHOD_ATTRIBUTE_VTABLE_LAYOUT_MASK) == consts.METHOD_ATTRIBUTE_NEW_SLOT:
            text += "virtual "
        else:
            text += "override "
    if flags & consts.METHOD_ATTRIBUTE_PINVOKE_IMPL:
        text += "extern "
    cache[key] = text
    return text


def escape_string(value: str) -> str:
    out = []
    for char in value:
        if char == "'":
            out.append("\\'")
        elif char == '"':
            out.append('\\"')
        elif char == "\\":
            out.append("\\\\")
        elif char == "\0":
            out.append("\\0")
        elif char == "\a":
            out.append("\\a")
        elif char == "\b":
            out.append("\\b")
        elif char == "\f":
            out.append("\\f")
        elif char == "\n":
            out.append("\\n")
        elif char == "\r":
            out.append("\\r")
        elif char == "\t":
            out.append("\\t")
        elif char == "\v":
            out.append("\\v")
        elif ord(char) < 0x20 or ord(char) == 0x7F:
            out.append("\\x%02x" % ord(char))
        else:
            out.append(char)
    return "".join(out)


def format_constant(ok: bool, value: Any) -> str:
    if not ok:
        return "/*Metadata offset 0x%X*/" % (value if isinstance(value, int) else 0)
    if isinstance(value, str):
        return '"%s"' % escape_string(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        return repr(value)
    if value is None:
        return "null"
    return str(value)
