package dev.annati.il2cppdumper.dumper

import java.io.File

/**
 * Writes `dump.cs`, `stringliteral.json` and a minimal `il2cpp.h` on-device.
 *
 * On-device we run in metadata mode: names, flags and structure are recovered;
 * type signatures degrade to `/* TypeIndex: N */` markers and RVAs are omitted.
 *
 * Developed by Mohamed Annati.
 */
object DumpWriter {

    private const val VISIBILITY_MASK = 0x7
    private const val TYPE_PUBLIC = 0x1
    private const val TYPE_NESTED_PUBLIC = 0x2
    private const val TYPE_NESTED_PRIVATE = 0x3
    private const val TYPE_NESTED_FAMILY = 0x4
    private const val TYPE_NESTED_ASSEMBLY = 0x5
    private const val TYPE_NESTED_FAM_AND_ASSEM = 0x6
    private const val TYPE_NESTED_FAM_OR_ASSEM = 0x7
    private const val TYPE_INTERFACE = 0x20
    private const val TYPE_ABSTRACT = 0x80
    private const val TYPE_SEALED = 0x100

    private const val METHOD_ACCESS_MASK = 0x7
    private const val M_PRIVATE = 0x1; private const val M_PUBLIC = 0x6
    private const val M_FAMILY = 0x4; private const val M_ASSEM = 0x3
    private const val M_FAM_AND_ASSEM = 0x2; private const val M_FAM_OR_ASSEM = 0x5
    private const val M_STATIC = 0x10; private const val M_FINAL = 0x20
    private const val M_VIRTUAL = 0x40; private const val M_ABSTRACT = 0x400
    private const val M_VTABLE_MASK = 0x100; private const val M_NEW_SLOT = 0x100
    private const val M_PINVOKE = 0x2000

    private const val FIELD_ACCESS_MASK = 0x7
    private const val F_PRIVATE = 0x1; private const val F_PUBLIC = 0x6
    private const val F_FAMILY = 0x4; private const val F_ASSEMBLY = 0x3
    private const val F_FAM_AND_ASSEM = 0x2; private const val F_FAM_OR_ASSEM = 0x5
    private const val F_STATIC = 0x10; private const val F_INIT_ONLY = 0x20
    private const val F_LITERAL = 0x40

    fun write(metadata: Metadata, outDir: File): List<File> {
        outDir.mkdirs()
        val files = ArrayList<File>()

        val dump = File(outDir, "dump.cs")
        dump.writeText(dumpCs(metadata).toString())
        files.add(dump)

        val literals = File(outDir, "stringliteral.json")
        literals.writeText(stringLiterals(metadata).toString())
        files.add(literals)

        val header = File(outDir, "il2cpp.h")
        header.writeText(HEADER_TEXT)
        files.add(header)

        return files
    }

    private fun dumpCs(metadata: Metadata): StringBuilder = StringBuilder().apply {
        val meta = metadata
        append("// Generated by IL2CPP Dumper Studio (Android)\n")
        append("// Developer: @c0derz\n")
        append("// Metadata version: ${meta.version} | Mode: metadata\n")

        for ((index, image) in meta.imageDefs.withIndex()) {
            append("// Image $index: ${meta.string(image["nameIndex"] as Long)} - ${image["typeStart"]}\n")
        }

        for (image in meta.imageDefs) {
            val start = (image["typeStart"] as Long).toInt()
            val count = (image["typeCount"] as Long).toInt()
            for (t in start until minOf(start + count, meta.typeDefs.size)) {
                val typeDef = meta.typeDefs[t]
                val flags = (typeDef["flags"] as Long).toInt()
                val bitfield = (typeDef["bitfield"] as Long).toInt()
                val isValue = (bitfield and 0x1) == 1
                val isEnum = ((bitfield shr 1) and 0x1) == 1

                append("\n// Namespace: ${meta.string(typeDef["namespaceIndex"] as Long)}\n")
                append(visibility(flags))
                append(kindPrefix(flags, isValue, isEnum))
                append(kindWord(flags, isValue, isEnum))
                append(meta.typeName(typeDef))
                append(" // TypeDefIndex: $t\n{")

                // fields
                val fc = (typeDef["field_count"] as Long).toInt()
                val fs = (typeDef["fieldStart"] as Long).toInt()
                if (fc > 0) {
                    append("\n\t// Fields\n")
                    for (i in fs until minOf(fs + fc, meta.fieldDefs.size)) {
                        val field = meta.fieldDefs[i]
                        val fattrs = 0 // metadata mode: field attribute lives in binary type table
                        append("\tprivate object ${meta.string(field["nameIndex"] as Long)}")
                        append(" /* TypeIndex: ${field["typeIndex"]} */;\n")
                    }
                }

                // properties
                val pc = (typeDef["property_count"] as Long).toInt()
                val ps = (typeDef["propertyStart"] as Long).toInt()
                if (pc > 0) {
                    append("\n\t// Properties\n")
                    for (i in ps until minOf(ps + pc, meta.propertyDefs.size)) {
                        val prop = meta.propertyDefs[i]
                        append("\tobject ${meta.string(prop["nameIndex"] as Long)} { ")
                        if ((prop["get"] as Long) >= 0) append("get; ")
                        if ((prop["set"] as Long) >= 0) append("set; ")
                        append("}\n")
                    }
                }

                // events
                val ec = (typeDef["event_count"] as Long).toInt()
                val es = (typeDef["eventStart"] as Long).toInt()
                if (ec > 0) {
                    append("\n\t// Events\n")
                    for (i in es until minOf(es + ec, meta.eventDefs.size)) {
                        val ev = meta.eventDefs[i]
                        append("\tobject ${meta.string(ev["nameIndex"] as Long)};\n")
                    }
                }

                // methods
                val mc = (typeDef["method_count"] as Long).toInt()
                val ms = (typeDef["methodStart"] as Long).toInt()
                if (mc > 0) {
                    append("\n\t// Methods\n")
                    for (i in ms until minOf(ms + mc, meta.methodDefs.size)) {
                        val method = meta.methodDefs[i]
                        val mflags = (method["flags"] as Long).toInt()
                        val isAbstract = (mflags and M_ABSTRACT) != 0
                        append("\n\t${methodModifiers(mflags)}object ${meta.string(method["nameIndex"] as Long)}(")
                        val params = StringBuilder()
                        val pc2 = (method["parameterCount"] as Long).toInt()
                        val pstart = (method["parameterStart"] as Long).toInt()
                        for (j in 0 until pc2) {
                            val pIndex = pstart + j
                            if (pIndex >= meta.parameterDefs.size) break
                            val param = meta.parameterDefs[pIndex]
                            if (params.isNotEmpty()) params.append(", ")
                            params.append("object /* TypeIndex: ${param["typeIndex"]} */ ")
                            params.append(meta.string(param["nameIndex"] as Long))
                        }
                        append(params)
                        append(if (isAbstract) ");\n" else ") { }\n")
                    }
                }
                append("}\n")
            }
        }
    }

    private fun visibility(flags: Int): String = when (flags and VISIBILITY_MASK) {
        TYPE_PUBLIC, TYPE_NESTED_PUBLIC -> "public "
        TYPE_NESTED_PRIVATE -> "private "
        TYPE_NESTED_FAMILY -> "protected "
        TYPE_NESTED_FAM_OR_ASSEM -> "protected internal "
        else -> "internal "
    }

    private fun kindPrefix(flags: Int, isValue: Boolean, isEnum: Boolean): String {
        val abstract = flags and TYPE_ABSTRACT != 0
        val sealed = flags and TYPE_SEALED != 0
        return when {
            abstract && sealed -> "static "
            flags and TYPE_INTERFACE == 0 && abstract -> "abstract "
            !isValue && !isEnum && sealed -> "sealed "
            else -> ""
        }
    }

    private fun kindWord(flags: Int, isValue: Boolean, isEnum: Boolean): String = when {
        flags and TYPE_INTERFACE != 0 -> "interface "
        isEnum -> "enum "
        isValue -> "struct "
        else -> "class "
    }

    private fun methodModifiers(flags: Int): String {
        val sb = StringBuilder()
        when (flags and METHOD_ACCESS_MASK) {
            M_PRIVATE -> sb.append("private ")
            M_PUBLIC -> sb.append("public ")
            M_FAMILY -> sb.append("protected ")
            M_ASSEM, M_FAM_AND_ASSEM -> sb.append("internal ")
            M_FAM_OR_ASSEM -> sb.append("protected internal ")
        }
        if (flags and M_STATIC != 0) sb.append("static ")
        if (flags and M_ABSTRACT != 0) {
            sb.append("abstract ")
            if (flags and M_VTABLE_MASK == 0) sb.append("override ")
        } else if (flags and M_FINAL != 0) {
            if (flags and M_VTABLE_MASK == 0) sb.append("sealed override ")
        } else if (flags and M_VIRTUAL != 0) {
            sb.append(if (flags and M_VTABLE_MASK == M_NEW_SLOT) "virtual " else "override ")
        }
        if (flags and M_PINVOKE != 0) sb.append("extern ")
        return sb.toString()
    }

    private fun stringLiterals(metadata: Metadata): StringBuilder = StringBuilder().apply {
        append("[")
        for ((i, _) in metadata.stringLiterals.withIndex()) {
            if (i > 0) append(",")
            append("\n  ").append(jsonString(metadata.stringLiteral(i)))
        }
        append("\n]")
    }

    private val HEADER_TEXT = """
#pragma once
/* il2cpp.h - generated by IL2CPP Dumper Studio (Android)
 * Developer: @c0derz
 */
typedef void(*Il2CppMethodPointer)();
struct MethodInfo;
struct Il2CppClass;
struct Il2CppType { void* data; unsigned int bits; };
struct Il2CppObject { Il2CppClass* klass; void* monitor; };
"""

    private fun jsonString(s: String): String {
        val sb = StringBuilder("\"")
        for (c in s) {
            when (c) {
                '\\' -> sb.append("\\\\")
                '"' -> sb.append("\\\"")
                '\n' -> sb.append("\\n")
                '\r' -> sb.append("\\r")
                '\t' -> sb.append("\\t")
                else -> if (c.code < 0x20) sb.append("\\u%04x".format(c.code)) else sb.append(c)
            }
        }
        return sb.append('"').toString()
    }
}
